///* AUTO-GENERATED FILE.  DO NOT MODIFY.
//// *
//// * This class was automatically generated by the
//// * gradle plugin from the resource data it found. It
//// * should not be modified by hand.
//// */
////package android.support.coreutils;
////
////public final class R {
////    public static final class attr {
////        public static final int font = 0x7f020076;
////        public static final int fontProviderAuthority = 0x7f020078;
////        public static final int fontProviderCerts = 0x7f020079;
////        public static final int fontProviderFetchStrategy = 0x7f02007a;
////        public static final int fontProviderFetchTimeout = 0x7f02007b;
////        public static final int fontProviderPackage = 0x7f02007c;
////        public static final int fontProviderQuery = 0x7f02007d;
////        public static final int fontStyle = 0x7f02007e;
////        public static final int fontWeight = 0x7f02007f;
////    }
////    public static final class bool {
////        public static final int abc_action_bar_embed_tabs = 0x7f030000;
////    }
////    public static final class color {
////        public static final int notification_action_color_